language: python

python:
  - "3.6"

services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="mysite.settings"
    - PYTHONPATH="/home/travis/build/alextwilson/same-page"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.11.6 DB=mysql

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO

before_script:
  - mysql -e 'create database travis_ci_db;'

#command to run the test suite
script:
  - python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: HEROKU_API_KEY
  app: rocky-plateau-76522
